baseURL = "https://catalystdatascience.com/"
disqusShortname = ""
googleAnalytics = "G-5YYD8J9V48"
paginate = "3"
summaryLength = "15"
theme = "bigspring-light"
title = "Catalyst Data Science"
[markup.goldmark.renderer]
unsafe = true
