baseURL = "http://demo.gethugothemes.com/bigspring-light/examplesite/"
disqusShortname = ""
googleAnalytics = "G-5YYD8J9V48"
paginate = "3"
summaryLength = "15"
theme = "bigspring-light"
title = "Bigspring Light"
[markup.goldmark.renderer]
unsafe = true
