############################# English ############################
[en]
languageName = "En"
title = "Catalyst"
contentDir = "content/english" # content/english
weight = 1
########### footer content ##########
footer_menu_left = "Company"
footer_menu_middle = "Product"
footer_menu_right = "Support"
footer_content = "Data that works for you."
# copyright
copyright = "Made in Maine, USA.\nCopyright (c) 2022 Catalyst Data Science"



############################# Deutsch ############################
#[de]
#languageName = "De"
#title = "Bigspring Hugo"
#contentDir = "content/english" # content/german
#weight = 2
########### footer content ##########
#footer_menu_left = "Firma"
#footer_menu_middle = "Produkte"
#footer_menu_right = "Support"
#footer_content = "Lorem ipsum dolor sit amet, consectetur elit. Consjat tristique eget amet, tempus eu at cttur."
# copyright
# copyright = "Design von [Themefisher](https://themefisher.com/) Entwickelt von [Gethugothemes](https://gethugothemes.com/)"
