author = "Catalyst Data Science"
blogCategoryType = "category"
contact_form_action = "#"
description = "This is meta description"
image = "images/logo.png"
logo = "images/logo.png"
logo_width = "150px"
[cookies]
button = "I Accept"
content = "This site uses cookies. By continuing to use this website, you agree to their use."
enable = false
expire_days = 2
[navigation_button]
enable = true
label = "Get Started"
link = "contact"
[preloader]
enable = false
preloader = ""
[[social]]
icon = "fab fa-twitter"
link = "https://twitter.com/catalystdatasci"
title = "twitter"
